spring.application.name: kafka-service
server.port: 8083
spring.output.ansi.enabled: always



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #    show-sql: true
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: my-group
      max-poll-records: 1000
    producer:
      bootstrap-servers: localhost:29092
      retries: 3
      acks: 1
      batch-size: 100000
      compression-type: lz4
    listener:
      concurrency: 5

#logging:
#  level:
#    org:
#      hibernate:
#        SQL : DEBUG

management.endpoint.metrics.enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"