spring.application.name: customer-service-grpc
spring.output.ansi.enabled: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #    show-sql: true
    hibernate:
      ddl-auto: create

#logging:
#  level:
#    org:
#      hibernate:
#        SQL : DEBUG


management.endpoint.metrics.enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


server.port: 8083
grpc.server.port: 9094


