spring.application.name: customer-service
spring.output.ansi.enabled: always

management.endpoint.metrics.enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


server.port: 8082
