{
 "title": "Spring Boot HTTP",
 "description": "Spring Boot (Micrometer) with HTTP requests.",
 "tags": [
  "prometheus",
  "spring-boot",
  "micrometer",
  "http"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_max, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(http_server_requests_seconds_max{namespace=\"$namespace\"}, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_seconds_max{namespace=\"$namespace\", application=\"$application\"}, instance)"
    }
   },
   {
    "name": "uri",
    "label": "URI",
    "query": {
     "query": "label_values(http_server_requests_seconds_max{namespace=\"$namespace\",application=\"$application\", instance=~\"$instance\"}, uri)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(http_server_requests_seconds_max{namespace=\"$namespace\",application=\"$application\", instance=~\"$instance\", uri=~\"$uri\"}, status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration of SUCCESSful requests",
   "type": "timeseries",
   "description": "Duration of HTTP server request handling without exception.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", uri!~\"/actuator.*\", status=~\"$status\", exception=~\"None|none\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", uri!~\"/actuator.*\", status=~\"$status\", exception=~\"None|none\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{uri}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Duration of FAILED requests",
   "type": "timeseries",
   "description": "Duration of HTTP server request handling with exception.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", uri!~\"/actuator.*\", status=~\"$status\", exception!~\"None\", exception!~\"none\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", uri!~\"/actuator.*\", status=~\"$status\", exception!~\"None\", exception!~\"none\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{uri}} [{{status}}]: {{exception}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Requests per seconds",
   "type": "timeseries",
   "description": "Number of requests per seconds.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", uri!~\"/actuator.*\", status=~\"$status\"}[1m])",
     "legendFormat": "{{method}} {{uri}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Mean response time",
   "type": "timeseries",
   "description": "Mean time on request response.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"$uri\", uri!~\"/actuator.*\", status=~\"$status\"}[1m])",
     "legendFormat": "{{method}} {{uri}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Actuator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration of actuator",
     "type": "timeseries",
     "description": "Duration of actuator request handling.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"/actuator.*\", status=~\"$status\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", uri=~\"/actuator.*\", status=~\"$status\"}[$__rate_interval])",
       "legendFormat": "{{method}} {{uri}} [{{status}}]"
      }
     ]
    }
   ]
  }
 ]
}