version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.7
    ports:
      - "29092:29092"
#    volumes:
#      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_BACKGROUND_THREADS=20
      - KAFKA_CFG_CONFLUENT_BALANCER_DISK_MAX_LOAD=1.0
      - KAFKA_CFG_CONFLUENT_BALANCER_ENABLE=true
      - KAFKA_CFG_NUM_IO_THREADS=16
      - KAFKA_CFG_NUM_NETWORK_THREADS=9
      - KAFKA_CFG_NUM_REPLICA_FETCHERS=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=5
      - KAFKA_CFG_ZOOKEEPER_MAX_IN_FLIGHT_REQUESTS=20
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_LOG_RETENTION_MS=10000
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
#volumes:
#  kafka_data:
#    driver: local

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/dashboards/main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning