spring.application.name: account-service-grpc
spring.output.ansi.enabled: always

#management.endpoints.web.exposure.include: metrics
management.endpoint.metrics.enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
grpc.server.port: 9091

