spring.application.name: grpcLinear-core
server.port: 8088
grpc.server.port: 9068
spring.output.ansi.enabled: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    hibernate:
      ddl-auto: create

#logging:
#  level:
#    org:
#      hibernate:
#        SQL : DEBUG

management.endpoint.metrics.enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
grpc:
  client:
    product-service:
      address: 'localhost:9069'
      negotiation-type: plaintext
