spring.application.name: grpcLinear-payment-service
server.port: 8090
grpc.server.port: 9060
spring.output.ansi.enabled: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

management.endpoint.metrics.enabled: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

